apiVersion: v2
name: chart
description: Helm chart for the template-k8s operator.
type: application
version: 0.1.2 # x-release-please-version
appVersion: "v0.1.2" # x-release-please-version
kubeVersion: ">= 1.29.0-0"
home: https://github.com/meigma/template-k8s
sources:
  - https://github.com/meigma/template-k8s
maintainers:
  - name: meigma
