version: 2

project_name: yacd

builds:
  - id: yacd
    main: ./cmd
    binary: yacd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: yacd
    ids:
      - yacd
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

sboms:
  - id: binary
    artifacts: binary

changelog:
  disable: true

release:
  disable: true
