template: testify
formatter: goimports
dir: cli/internal/mocks
filename: '{{.InterfaceName | snakecase}}.go'
pkgname: mocks
structname: '{{.InterfaceName}}'
force-file-write: true
packages:
  github.com/meigma/yacd/cli/internal/kube:
    interfaces:
      Client:
      ForwardSession:
  github.com/meigma/yacd/cli/internal/cli:
    interfaces:
      UTxOConfirmer:
  github.com/meigma/yacd/internal/cardano/tx:
    interfaces:
      Submitter:
  github.com/meigma/yacd/cli/internal/operator:
    interfaces:
      Installer:
  github.com/meigma/yacd/cli/internal/toolbin:
    interfaces:
      Resolver:
  github.com/meigma/yacd/cli/internal/cluster:
    interfaces:
      Provisioner:
  github.com/meigma/yacd/cli/internal/clusterstate:
    interfaces:
      Store:
