{{- if and .Values.rbac.create .Values.metrics.enabled .Values.metrics.secure }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "yacd.metricsAuthRoleName" . }}
  labels:
    {{- include "yacd.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "yacd.metricsAuthRoleBindingName" . }}
  labels:
    {{- include "yacd.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "yacd.metricsAuthRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yacd.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
