{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template-k8s.managerRoleName" . }}
  labels:
    {{- include "template-k8s.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - example.meigma.io
    resources:
      - nginxdeployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - example.meigma.io
    resources:
      - nginxdeployments/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template-k8s.managerRoleBindingName" . }}
  labels:
    {{- include "template-k8s.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "template-k8s.managerRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "template-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
