{{- if and .Values.rbac.create .Values.rbac.metricsReader.create .Values.metrics.enabled .Values.metrics.secure }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template-k8s.metricsReaderRoleName" . }}
  labels:
    {{- include "template-k8s.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}
