// Package config builds a validated publisher runtime configuration
// from a Viper instance that has already been bound to the publish
// subcommand's flags (and therefore transparently reads the matching
// YACD_* environment variables).
package config

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/viper"
)

// Default mount paths for the projected ServiceAccount the publisher
// uses when running as a Pod init container. These are the standard
// Kubernetes locations and apply when the corresponding flag is left
// empty.
const (
	// DefaultServiceTokenPath is the standard mount path for a Pod's
	// projected ServiceAccount bearer token.
	DefaultServiceTokenPath = "/var/run/secrets/kubernetes.io/serviceaccount/token"
	// DefaultServiceCAPath is the standard mount path for the
	// Kubernetes API CA bundle inside a Pod.
	DefaultServiceCAPath = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
	// DefaultNamespacePath is the standard mount path for the file
	// containing the Pod's own namespace.
	DefaultNamespacePath = "/var/run/secrets/kubernetes.io/serviceaccount/namespace"
)

// Config is the validated publisher runtime configuration produced by
// [Load]. All fields are populated after derivation rules and
// validation have been applied, so consumers can trust the values
// without performing further normalization.
type Config struct {
	// ArtifactConfigMapName is the name of the network artifact
	// ConfigMap the publisher will patch.
	ArtifactConfigMapName string
	// ArtifactConfigMapNamespace is the namespace of the target
	// ConfigMap. When empty in input, it is read from the projected
	// namespace file at ArtifactNamespacePath.
	ArtifactConfigMapNamespace string
	// ArtifactTokenPath is the filesystem path to the projected
	// ServiceAccount bearer token used to authenticate the PATCH.
	ArtifactTokenPath string
	// ArtifactCAPath is the filesystem path to the projected
	// Kubernetes API CA bundle used for TLS verification.
	ArtifactCAPath string
	// ArtifactNamespacePath is the filesystem path to the file holding
	// the Pod's namespace. Used as the fallback source for
	// ArtifactConfigMapNamespace.
	ArtifactNamespacePath string
	// KubernetesAPIURL is the base URL of the Kubernetes API server,
	// with any trailing slash trimmed. When empty in input, it is
	// derived from the pod-injected KUBERNETES_SERVICE_HOST and
	// KUBERNETES_SERVICE_PORT[_HTTPS] environment variables.
	KubernetesAPIURL string
	// LocalnetEnvDir is the directory containing the localnet
	// environment generated by cardano-testnet.
	LocalnetEnvDir string
	// LocalnetPlanManifestFile is the absolute path of the localnet
	// plan manifest emitted alongside the generated environment.
	LocalnetPlanManifestFile string
	// CardanoNetworkName is the name of the owning CardanoNetwork
	// resource.
	CardanoNetworkName string
	// CardanoNetworkNamespace is the namespace of the owning
	// CardanoNetwork resource. When empty in input, it defaults to
	// ArtifactConfigMapNamespace.
	CardanoNetworkNamespace string
	// CardanoNetworkMode is the network mode (e.g. "local", "public")
	// recorded in the published connection metadata.
	CardanoNetworkMode string
	// CardanoNetworkEra is the Cardano era recorded in the published
	// connection metadata.
	CardanoNetworkEra string
	// CardanoNodeToNodeHost is the hostname clients use to reach the
	// primary node's node-to-node Service.
	CardanoNodeToNodeHost string
	// CardanoNodeToNodePort is the TCP port clients use to reach the
	// primary node's node-to-node Service. Valid range is 1-65535.
	CardanoNodeToNodePort int
	// CardanoNodeToNodeURL is the full URL clients use to reach the
	// primary node's node-to-node Service. When empty in input and both
	// host and port are set, it is synthesized as "tcp://<host>:<port>".
	CardanoNodeToNodeURL string
}

// Load reads, derives, and validates the publisher configuration from
// vp. The returned Config is safe to use; on error the zero value is
// returned along with a descriptive message naming the offending flag.
//
// Derivation rules applied before validation:
//   - Empty path fields fall back to their projected-ServiceAccount defaults.
//   - An empty ArtifactConfigMapNamespace is read from the projected
//     namespace file at ArtifactNamespacePath.
//   - An empty CardanoNetworkNamespace defaults to ArtifactConfigMapNamespace.
//   - An empty KubernetesAPIURL is derived from the standard pod-injected
//     KUBERNETES_SERVICE_HOST / _PORT[_HTTPS] environment variables.
//   - An empty CardanoNodeToNodeURL is synthesized as "tcp://<host>:<port>"
//     when host and port are both supplied.
func Load(vp *viper.Viper) (Config, error) {
	cfg := Config{
		ArtifactConfigMapName:      strings.TrimSpace(vp.GetString("artifact-configmap-name")),
		ArtifactConfigMapNamespace: strings.TrimSpace(vp.GetString("artifact-configmap-namespace")),
		ArtifactTokenPath:          strings.TrimSpace(vp.GetString("artifact-token-path")),
		ArtifactCAPath:             strings.TrimSpace(vp.GetString("artifact-ca-path")),
		ArtifactNamespacePath:      strings.TrimSpace(vp.GetString("artifact-namespace-path")),
		KubernetesAPIURL:           strings.TrimRight(strings.TrimSpace(vp.GetString("kubernetes-api-url")), "/"),
		LocalnetEnvDir:             strings.TrimSpace(vp.GetString("localnet-env-dir")),
		LocalnetPlanManifestFile:   strings.TrimSpace(vp.GetString("localnet-plan-manifest-file")),
		CardanoNetworkName:         strings.TrimSpace(vp.GetString("cardano-network-name")),
		CardanoNetworkNamespace:    strings.TrimSpace(vp.GetString("cardano-network-namespace")),
		CardanoNetworkMode:         strings.TrimSpace(vp.GetString("cardano-network-mode")),
		CardanoNetworkEra:          strings.TrimSpace(vp.GetString("cardano-network-era")),
		CardanoNodeToNodeHost:      strings.TrimSpace(vp.GetString("cardano-node-to-node-host")),
		CardanoNodeToNodePort:      vp.GetInt("cardano-node-to-node-port"),
		CardanoNodeToNodeURL:       strings.TrimSpace(vp.GetString("cardano-node-to-node-url")),
	}

	if cfg.ArtifactTokenPath == "" {
		cfg.ArtifactTokenPath = DefaultServiceTokenPath
	}
	if cfg.ArtifactCAPath == "" {
		cfg.ArtifactCAPath = DefaultServiceCAPath
	}
	if cfg.ArtifactNamespacePath == "" {
		cfg.ArtifactNamespacePath = DefaultNamespacePath
	}

	if cfg.ArtifactConfigMapNamespace == "" {
		ns, err := readTrimmedFile(cfg.ArtifactNamespacePath)
		if err != nil {
			return Config{}, fmt.Errorf("resolve artifact ConfigMap namespace from %s: %w", cfg.ArtifactNamespacePath, err)
		}
		cfg.ArtifactConfigMapNamespace = ns
	}

	if cfg.CardanoNetworkNamespace == "" {
		cfg.CardanoNetworkNamespace = cfg.ArtifactConfigMapNamespace
	}

	if cfg.KubernetesAPIURL == "" {
		cfg.KubernetesAPIURL = kubernetesAPIURLFromPodEnv()
	}

	if cfg.CardanoNodeToNodeURL == "" && cfg.CardanoNodeToNodeHost != "" && cfg.CardanoNodeToNodePort != 0 {
		cfg.CardanoNodeToNodeURL = fmt.Sprintf("tcp://%s:%d", cfg.CardanoNodeToNodeHost, cfg.CardanoNodeToNodePort)
	}

	if err := cfg.validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}

// validate returns an error when c is missing a required field or
// carries an out-of-range port. Error messages reference the
// user-facing flag name for each offending field.
func (c Config) validate() error {
	required := []struct {
		flag  string
		value string
	}{
		{"--artifact-configmap-name", c.ArtifactConfigMapName},
		{"--localnet-env-dir", c.LocalnetEnvDir},
		{"--localnet-plan-manifest-file", c.LocalnetPlanManifestFile},
		{"--cardano-network-name", c.CardanoNetworkName},
		{"--cardano-network-mode", c.CardanoNetworkMode},
		{"--cardano-network-era", c.CardanoNetworkEra},
		{"--cardano-node-to-node-host", c.CardanoNodeToNodeHost},
	}
	for _, r := range required {
		if r.value == "" {
			return fmt.Errorf("%s is required", r.flag)
		}
	}

	if c.ArtifactConfigMapNamespace == "" {
		return fmt.Errorf("--artifact-configmap-namespace or a readable --artifact-namespace-path is required")
	}
	if c.CardanoNodeToNodePort < 1 || c.CardanoNodeToNodePort > 65535 {
		return fmt.Errorf("--cardano-node-to-node-port must be a TCP port between 1 and 65535")
	}
	if c.CardanoNodeToNodeURL == "" {
		return fmt.Errorf("--cardano-node-to-node-url is required")
	}
	if c.KubernetesAPIURL == "" {
		return fmt.Errorf("--kubernetes-api-url or pod-injected KUBERNETES_SERVICE_HOST/PORT is required")
	}
	return nil
}

// kubernetesAPIURLFromPodEnv derives an in-cluster Kubernetes API base
// URL from the standard pod-injected service environment variables.
//
// The function reads KUBERNETES_SERVICE_HOST and prefers
// KUBERNETES_SERVICE_PORT_HTTPS, falling back to KUBERNETES_SERVICE_PORT
// and finally to 443. IPv6 hosts are wrapped in square brackets so the
// resulting URL is valid. An empty string is returned when host is
// unset, leaving validation to surface the missing-source error to the
// user.
func kubernetesAPIURLFromPodEnv() string {
	host := strings.TrimSpace(os.Getenv("KUBERNETES_SERVICE_HOST"))
	if host == "" {
		return ""
	}
	port := strings.TrimSpace(os.Getenv("KUBERNETES_SERVICE_PORT_HTTPS"))
	if port == "" {
		port = strings.TrimSpace(os.Getenv("KUBERNETES_SERVICE_PORT"))
	}
	if port == "" {
		port = "443"
	}
	if strings.Contains(host, ":") && !strings.HasPrefix(host, "[") {
		host = "[" + host + "]"
	}
	return "https://" + host + ":" + port
}

// readTrimmedFile reads the file at path and returns its contents with
// leading and trailing whitespace removed. Errors from [os.ReadFile]
// are returned unwrapped so callers can attach their own context.
func readTrimmedFile(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(raw)), nil
}
