apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: template-k8s-registry
port: 5005
listenAddress: 127.0.0.1
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-template-k8s-dev
product: kind
registry: template-k8s-registry
kindV1Alpha4Cluster:
  nodes:
    - role: control-plane
