package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

const (
	defaultServiceTokenPath = "/var/run/secrets/kubernetes.io/serviceaccount/token"
	defaultServiceCAPath    = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
	defaultNamespacePath    = "/var/run/secrets/kubernetes.io/serviceaccount/namespace"
)

func newPublishCommand(commandContext *commandContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "publish",
		Short: "Publish generated localnet artifacts to the network artifact ConfigMap",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			_, err := fmt.Fprintln(cmd.ErrOrStderr(), "publish: not yet implemented")
			return err
		},
	}

	flags := cmd.Flags()
	flags.String("artifact-configmap-name", "", "Name of the network artifact ConfigMap to patch")
	flags.String("artifact-configmap-namespace", "", "Namespace of the network artifact ConfigMap (defaults to the projected namespace file)")
	flags.String("artifact-token-path", defaultServiceTokenPath, "Path to the projected ServiceAccount token used to patch the ConfigMap")
	flags.String("artifact-ca-path", defaultServiceCAPath, "Path to the projected Kubernetes API CA bundle")
	flags.String("artifact-namespace-path", defaultNamespacePath, "Path to the projected namespace file used to resolve the ConfigMap namespace")
	flags.String("kubernetes-api-url", "", "Kubernetes API base URL (defaults to pod-injected service host/port)")
	flags.String("localnet-env-dir", "", "Directory containing the localnet environment generated by cardano-testnet")
	flags.String("localnet-plan-manifest-file", "", "Absolute path to the localnet plan manifest file")
	flags.String("cardano-network-name", "", "Name of the owning CardanoNetwork resource")
	flags.String("cardano-network-namespace", "", "Namespace of the owning CardanoNetwork resource (defaults to the artifact namespace)")
	flags.String("cardano-network-mode", "", "Network mode (e.g. local, public)")
	flags.String("cardano-network-era", "", "Cardano era for the published connection metadata")
	flags.String("cardano-node-to-node-host", "", "Primary node-to-node Service hostname")
	flags.Int("cardano-node-to-node-port", 0, "Primary node-to-node Service port")
	flags.String("cardano-node-to-node-url", "", "Pre-built primary node-to-node URL (defaults to tcp://<host>:<port>)")

	_ = commandContext
	return cmd
}
