apiVersion: yacd.meigma.io/devconfig/v1alpha1
kind: Environment
metadata:
  name: preprod-smoke
  namespace: yacd-smoke
spec:
  network:
    mode: public
    node:
      version: "11.0.1"
      port: 3001
      storage:
        size: 20Gi
    public:
      profile: preprod
