//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSync) DeepCopyInto(out *CardanoDBSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSync.
func (in *CardanoDBSync) DeepCopy() *CardanoDBSync {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CardanoDBSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncConfigSpec) DeepCopyInto(out *CardanoDBSyncConfigSpec) {
	*out = *in
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(CardanoDBSyncRuntimeSpec)
		**out = **in
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(CardanoDBSyncSnapshotSpec)
		**out = **in
	}
	if in.Insert != nil {
		in, out := &in.Insert, &out.Insert
		*out = new(CardanoDBSyncInsertSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IPFSGateways != nil {
		in, out := &in.IPFSGateways, &out.IPFSGateways
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncConfigSpec.
func (in *CardanoDBSyncConfigSpec) DeepCopy() *CardanoDBSyncConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncDatabaseSpec) DeepCopyInto(out *CardanoDBSyncDatabaseSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(CardanoDBSyncExternalDatabaseSpec)
		**out = **in
	}
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(CardanoDBSyncManagedDatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncDatabaseSpec.
func (in *CardanoDBSyncDatabaseSpec) DeepCopy() *CardanoDBSyncDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncDatabaseStatus) DeepCopyInto(out *CardanoDBSyncDatabaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncDatabaseStatus.
func (in *CardanoDBSyncDatabaseStatus) DeepCopy() *CardanoDBSyncDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncEndpointsStatus) DeepCopyInto(out *CardanoDBSyncEndpointsStatus) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncEndpointsStatus.
func (in *CardanoDBSyncEndpointsStatus) DeepCopy() *CardanoDBSyncEndpointsStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncEndpointsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncExternalDatabaseSpec) DeepCopyInto(out *CardanoDBSyncExternalDatabaseSpec) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncExternalDatabaseSpec.
func (in *CardanoDBSyncExternalDatabaseSpec) DeepCopy() *CardanoDBSyncExternalDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncExternalDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncFollowerNodeSpec) DeepCopyInto(out *CardanoDBSyncFollowerNodeSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(CardanoDBSyncStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncFollowerNodeSpec.
func (in *CardanoDBSyncFollowerNodeSpec) DeepCopy() *CardanoDBSyncFollowerNodeSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncFollowerNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncInsertSpec) DeepCopyInto(out *CardanoDBSyncInsertSpec) {
	*out = *in
	if in.TxCBOR != nil {
		in, out := &in.TxCBOR, &out.TxCBOR
		*out = new(bool)
		**out = **in
	}
	if in.TxOut != nil {
		in, out := &in.TxOut, &out.TxOut
		*out = new(CardanoDBSyncTxOutSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ledger != nil {
		in, out := &in.Ledger, &out.Ledger
		*out = new(CardanoDBSyncLedgerMode)
		**out = **in
	}
	if in.Shelley != nil {
		in, out := &in.Shelley, &out.Shelley
		*out = new(CardanoDBSyncShelleyInsertSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiAsset != nil {
		in, out := &in.MultiAsset, &out.MultiAsset
		*out = new(CardanoDBSyncMultiAssetInsertSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(CardanoDBSyncMetadataInsertSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Plutus != nil {
		in, out := &in.Plutus, &out.Plutus
		*out = new(CardanoDBSyncPlutusInsertSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(bool)
		**out = **in
	}
	if in.OffchainPoolData != nil {
		in, out := &in.OffchainPoolData, &out.OffchainPoolData
		*out = new(bool)
		**out = **in
	}
	if in.OffchainVoteData != nil {
		in, out := &in.OffchainVoteData, &out.OffchainVoteData
		*out = new(bool)
		**out = **in
	}
	if in.PoolStats != nil {
		in, out := &in.PoolStats, &out.PoolStats
		*out = new(bool)
		**out = **in
	}
	if in.JSONType != nil {
		in, out := &in.JSONType, &out.JSONType
		*out = new(CardanoDBSyncJSONType)
		**out = **in
	}
	if in.RemoveJSONBFromSchema != nil {
		in, out := &in.RemoveJSONBFromSchema, &out.RemoveJSONBFromSchema
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncInsertSpec.
func (in *CardanoDBSyncInsertSpec) DeepCopy() *CardanoDBSyncInsertSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncInsertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncList) DeepCopyInto(out *CardanoDBSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CardanoDBSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncList.
func (in *CardanoDBSyncList) DeepCopy() *CardanoDBSyncList {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CardanoDBSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncManagedDatabaseSpec) DeepCopyInto(out *CardanoDBSyncManagedDatabaseSpec) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(CardanoDBSyncSecretReference)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(CardanoDBSyncStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(CardanoDBSyncPostgresParametersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncManagedDatabaseSpec.
func (in *CardanoDBSyncManagedDatabaseSpec) DeepCopy() *CardanoDBSyncManagedDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncManagedDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncMetadataInsertSpec) DeepCopyInto(out *CardanoDBSyncMetadataInsertSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncMetadataInsertSpec.
func (in *CardanoDBSyncMetadataInsertSpec) DeepCopy() *CardanoDBSyncMetadataInsertSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncMetadataInsertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncMultiAssetInsertSpec) DeepCopyInto(out *CardanoDBSyncMultiAssetInsertSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncMultiAssetInsertSpec.
func (in *CardanoDBSyncMultiAssetInsertSpec) DeepCopy() *CardanoDBSyncMultiAssetInsertSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncMultiAssetInsertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncNetworkReference) DeepCopyInto(out *CardanoDBSyncNetworkReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncNetworkReference.
func (in *CardanoDBSyncNetworkReference) DeepCopy() *CardanoDBSyncNetworkReference {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncNetworkReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncPlacementSpec) DeepCopyInto(out *CardanoDBSyncPlacementSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncPlacementSpec.
func (in *CardanoDBSyncPlacementSpec) DeepCopy() *CardanoDBSyncPlacementSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncPlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncPlacementStatus) DeepCopyInto(out *CardanoDBSyncPlacementStatus) {
	*out = *in
	if in.PrimarySidecar != nil {
		in, out := &in.PrimarySidecar, &out.PrimarySidecar
		*out = new(CardanoDBSyncPrimarySidecarStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncPlacementStatus.
func (in *CardanoDBSyncPlacementStatus) DeepCopy() *CardanoDBSyncPlacementStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncPlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncPlutusInsertSpec) DeepCopyInto(out *CardanoDBSyncPlutusInsertSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ScriptHashes != nil {
		in, out := &in.ScriptHashes, &out.ScriptHashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncPlutusInsertSpec.
func (in *CardanoDBSyncPlutusInsertSpec) DeepCopy() *CardanoDBSyncPlutusInsertSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncPlutusInsertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncPostgresParametersSpec) DeepCopyInto(out *CardanoDBSyncPostgresParametersSpec) {
	*out = *in
	if in.MaintenanceWorkMem != nil {
		in, out := &in.MaintenanceWorkMem, &out.MaintenanceWorkMem
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxParallelMaintenanceWorkers != nil {
		in, out := &in.MaxParallelMaintenanceWorkers, &out.MaxParallelMaintenanceWorkers
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncPostgresParametersSpec.
func (in *CardanoDBSyncPostgresParametersSpec) DeepCopy() *CardanoDBSyncPostgresParametersSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncPostgresParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncPrimarySidecarResourcesStatus) DeepCopyInto(out *CardanoDBSyncPrimarySidecarResourcesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncPrimarySidecarResourcesStatus.
func (in *CardanoDBSyncPrimarySidecarResourcesStatus) DeepCopy() *CardanoDBSyncPrimarySidecarResourcesStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncPrimarySidecarResourcesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncPrimarySidecarStatus) DeepCopyInto(out *CardanoDBSyncPrimarySidecarStatus) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncPrimarySidecarStatus.
func (in *CardanoDBSyncPrimarySidecarStatus) DeepCopy() *CardanoDBSyncPrimarySidecarStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncPrimarySidecarStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncProgressStatus) DeepCopyInto(out *CardanoDBSyncProgressStatus) {
	*out = *in
	if in.NodeBlockHeight != nil {
		in, out := &in.NodeBlockHeight, &out.NodeBlockHeight
		*out = new(int64)
		**out = **in
	}
	if in.DBBlockHeight != nil {
		in, out := &in.DBBlockHeight, &out.DBBlockHeight
		*out = new(int64)
		**out = **in
	}
	if in.DBSlotHeight != nil {
		in, out := &in.DBSlotHeight, &out.DBSlotHeight
		*out = new(int64)
		**out = **in
	}
	if in.DBQueueLength != nil {
		in, out := &in.DBQueueLength, &out.DBQueueLength
		*out = new(int64)
		**out = **in
	}
	if in.LagBlocks != nil {
		in, out := &in.LagBlocks, &out.LagBlocks
		*out = new(int64)
		**out = **in
	}
	if in.Epoch != nil {
		in, out := &in.Epoch, &out.Epoch
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncProgressStatus.
func (in *CardanoDBSyncProgressStatus) DeepCopy() *CardanoDBSyncProgressStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncProgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncRuntimeSpec) DeepCopyInto(out *CardanoDBSyncRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncRuntimeSpec.
func (in *CardanoDBSyncRuntimeSpec) DeepCopy() *CardanoDBSyncRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncSecretKeyReference) DeepCopyInto(out *CardanoDBSyncSecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncSecretKeyReference.
func (in *CardanoDBSyncSecretKeyReference) DeepCopy() *CardanoDBSyncSecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncSecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncSecretReference) DeepCopyInto(out *CardanoDBSyncSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncSecretReference.
func (in *CardanoDBSyncSecretReference) DeepCopy() *CardanoDBSyncSecretReference {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncShelleyInsertSpec) DeepCopyInto(out *CardanoDBSyncShelleyInsertSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.StakeAddresses != nil {
		in, out := &in.StakeAddresses, &out.StakeAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncShelleyInsertSpec.
func (in *CardanoDBSyncShelleyInsertSpec) DeepCopy() *CardanoDBSyncShelleyInsertSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncShelleyInsertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncSnapshotSpec) DeepCopyInto(out *CardanoDBSyncSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncSnapshotSpec.
func (in *CardanoDBSyncSnapshotSpec) DeepCopy() *CardanoDBSyncSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncSpec) DeepCopyInto(out *CardanoDBSyncSpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(CardanoDBSyncPlacementSpec)
		**out = **in
	}
	if in.FollowerNode != nil {
		in, out := &in.FollowerNode, &out.FollowerNode
		*out = new(CardanoDBSyncFollowerNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Database.DeepCopyInto(&out.Database)
	if in.StateStorage != nil {
		in, out := &in.StateStorage, &out.StateStorage
		*out = new(CardanoDBSyncStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncSpec.
func (in *CardanoDBSyncSpec) DeepCopy() *CardanoDBSyncSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncStatus) DeepCopyInto(out *CardanoDBSyncStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(CardanoDBSyncEndpointsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(CardanoDBSyncDatabaseStatus)
		**out = **in
	}
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		*out = new(CardanoDBSyncProgressStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(CardanoDBSyncPlacementStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncStatus.
func (in *CardanoDBSyncStatus) DeepCopy() *CardanoDBSyncStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncStorageSpec) DeepCopyInto(out *CardanoDBSyncStorageSpec) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncStorageSpec.
func (in *CardanoDBSyncStorageSpec) DeepCopy() *CardanoDBSyncStorageSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoDBSyncTxOutSpec) DeepCopyInto(out *CardanoDBSyncTxOutSpec) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(CardanoDBSyncTxOutMode)
		**out = **in
	}
	if in.ForceTxIn != nil {
		in, out := &in.ForceTxIn, &out.ForceTxIn
		*out = new(bool)
		**out = **in
	}
	if in.UseAddressTable != nil {
		in, out := &in.UseAddressTable, &out.UseAddressTable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoDBSyncTxOutSpec.
func (in *CardanoDBSyncTxOutSpec) DeepCopy() *CardanoDBSyncTxOutSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoDBSyncTxOutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetwork) DeepCopyInto(out *CardanoNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetwork.
func (in *CardanoNetwork) DeepCopy() *CardanoNetwork {
	if in == nil {
		return nil
	}
	out := new(CardanoNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CardanoNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkArtifactsStatus) DeepCopyInto(out *CardanoNetworkArtifactsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkArtifactsStatus.
func (in *CardanoNetworkArtifactsStatus) DeepCopy() *CardanoNetworkArtifactsStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkArtifactsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkEndpointsStatus) DeepCopyInto(out *CardanoNetworkEndpointsStatus) {
	*out = *in
	if in.NodeToNode != nil {
		in, out := &in.NodeToNode, &out.NodeToNode
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
	if in.Ogmios != nil {
		in, out := &in.Ogmios, &out.Ogmios
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
	if in.Kupo != nil {
		in, out := &in.Kupo, &out.Kupo
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkEndpointsStatus.
func (in *CardanoNetworkEndpointsStatus) DeepCopy() *CardanoNetworkEndpointsStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkEndpointsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkIdentityStatus) DeepCopyInto(out *CardanoNetworkIdentityStatus) {
	*out = *in
	if in.NetworkMagic != nil {
		in, out := &in.NetworkMagic, &out.NetworkMagic
		*out = new(int64)
		**out = **in
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(PublicNetworkProfile)
		**out = **in
	}
	if in.Era != nil {
		in, out := &in.Era, &out.Era
		*out = new(CardanoEra)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkIdentityStatus.
func (in *CardanoNetworkIdentityStatus) DeepCopy() *CardanoNetworkIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkList) DeepCopyInto(out *CardanoNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CardanoNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkList.
func (in *CardanoNetworkList) DeepCopy() *CardanoNetworkList {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CardanoNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkSpec) DeepCopyInto(out *CardanoNetworkSpec) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalNetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(PublicNetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ChainAPI != nil {
		in, out := &in.ChainAPI, &out.ChainAPI
		*out = new(ChainAPISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkSpec.
func (in *CardanoNetworkSpec) DeepCopy() *CardanoNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkStatus) DeepCopyInto(out *CardanoNetworkStatus) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(CardanoNetworkIdentityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(CardanoNetworkEndpointsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(FaucetStatus)
		**out = **in
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = new(CardanoNetworkArtifactsStatus)
		**out = **in
	}
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		*out = new(CardanoNetworkSyncStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkStatus.
func (in *CardanoNetworkStatus) DeepCopy() *CardanoNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkSyncStatus) DeepCopyInto(out *CardanoNetworkSyncStatus) {
	*out = *in
	if in.Tip != nil {
		in, out := &in.Tip, &out.Tip
		*out = new(CardanoNetworkTipStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastTipUpdate != nil {
		in, out := &in.LastTipUpdate, &out.LastTipUpdate
		*out = (*in).DeepCopy()
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.NetworkSynchronization != nil {
		in, out := &in.NetworkSynchronization, &out.NetworkSynchronization
		*out = new(float64)
		**out = **in
	}
	if in.InferredTipSlot != nil {
		in, out := &in.InferredTipSlot, &out.InferredTipSlot
		*out = new(int64)
		**out = **in
	}
	if in.LagSlots != nil {
		in, out := &in.LagSlots, &out.LagSlots
		*out = new(int64)
		**out = **in
	}
	if in.LagSeconds != nil {
		in, out := &in.LagSeconds, &out.LagSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkSyncStatus.
func (in *CardanoNetworkSyncStatus) DeepCopy() *CardanoNetworkSyncStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkTipStatus) DeepCopyInto(out *CardanoNetworkTipStatus) {
	*out = *in
	if in.Slot != nil {
		in, out := &in.Slot, &out.Slot
		*out = new(int64)
		**out = **in
	}
	if in.BlockHeight != nil {
		in, out := &in.BlockHeight, &out.BlockHeight
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkTipStatus.
func (in *CardanoNetworkTipStatus) DeepCopy() *CardanoNetworkTipStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkTipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNodeSpec) DeepCopyInto(out *CardanoNodeSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(NodeStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNodeSpec.
func (in *CardanoNodeSpec) DeepCopy() *CardanoNodeSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainAPISpec) DeepCopyInto(out *ChainAPISpec) {
	*out = *in
	if in.Ogmios != nil {
		in, out := &in.Ogmios, &out.Ogmios
		*out = new(OgmiosSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kupo != nil {
		in, out := &in.Kupo, &out.Kupo
		*out = new(KupoSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(FaucetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainAPISpec.
func (in *ChainAPISpec) DeepCopy() *ChainAPISpec {
	if in == nil {
		return nil
	}
	out := new(ChainAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetSpec) DeepCopyInto(out *FaucetSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetSpec.
func (in *FaucetSpec) DeepCopy() *FaucetSpec {
	if in == nil {
		return nil
	}
	out := new(FaucetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetStatus) DeepCopyInto(out *FaucetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetStatus.
func (in *FaucetStatus) DeepCopy() *FaucetStatus {
	if in == nil {
		return nil
	}
	out := new(FaucetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KupoSpec) DeepCopyInto(out *KupoSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KupoSpec.
func (in *KupoSpec) DeepCopy() *KupoSpec {
	if in == nil {
		return nil
	}
	out := new(KupoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalGenesisSpec) DeepCopyInto(out *LocalGenesisSpec) {
	*out = *in
	if in.SecurityParameter != nil {
		in, out := &in.SecurityParameter, &out.SecurityParameter
		*out = new(int32)
		**out = **in
	}
	if in.MaxLovelaceSupply != nil {
		in, out := &in.MaxLovelaceSupply, &out.MaxLovelaceSupply
		*out = new(int64)
		**out = **in
	}
	if in.DelegatedSupply != nil {
		in, out := &in.DelegatedSupply, &out.DelegatedSupply
		*out = new(int64)
		**out = **in
	}
	if in.ProtocolVersion != nil {
		in, out := &in.ProtocolVersion, &out.ProtocolVersion
		*out = new(ProtocolVersionSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalGenesisSpec.
func (in *LocalGenesisSpec) DeepCopy() *LocalGenesisSpec {
	if in == nil {
		return nil
	}
	out := new(LocalGenesisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkSpec) DeepCopyInto(out *LocalNetworkSpec) {
	*out = *in
	out.Timing = in.Timing
	in.Topology.DeepCopyInto(&out.Topology)
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(LocalGenesisSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkSpec.
func (in *LocalNetworkSpec) DeepCopy() *LocalNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkTimingSpec) DeepCopyInto(out *LocalNetworkTimingSpec) {
	*out = *in
	out.SlotLength = in.SlotLength
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkTimingSpec.
func (in *LocalNetworkTimingSpec) DeepCopy() *LocalNetworkTimingSpec {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkTimingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkTopologySpec) DeepCopyInto(out *LocalNetworkTopologySpec) {
	*out = *in
	in.Pools.DeepCopyInto(&out.Pools)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkTopologySpec.
func (in *LocalNetworkTopologySpec) DeepCopy() *LocalNetworkTopologySpec {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPoolDefaultsSpec) DeepCopyInto(out *LocalPoolDefaultsSpec) {
	*out = *in
	if in.CostLovelace != nil {
		in, out := &in.CostLovelace, &out.CostLovelace
		*out = new(int64)
		**out = **in
	}
	if in.PledgeLovelace != nil {
		in, out := &in.PledgeLovelace, &out.PledgeLovelace
		*out = new(int64)
		**out = **in
	}
	if in.Margin != nil {
		in, out := &in.Margin, &out.Margin
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPoolDefaultsSpec.
func (in *LocalPoolDefaultsSpec) DeepCopy() *LocalPoolDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(LocalPoolDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPoolTopologySpec) DeepCopyInto(out *LocalPoolTopologySpec) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(LocalPoolDefaultsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPoolTopologySpec.
func (in *LocalPoolTopologySpec) DeepCopy() *LocalPoolTopologySpec {
	if in == nil {
		return nil
	}
	out := new(LocalPoolTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MithrilBootstrapSpec) DeepCopyInto(out *MithrilBootstrapSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MithrilBootstrapSpec.
func (in *MithrilBootstrapSpec) DeepCopy() *MithrilBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(MithrilBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigSource) DeepCopyInto(out *NetworkConfigSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigSource.
func (in *NetworkConfigSource) DeepCopy() *NetworkConfigSource {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStorageSpec) DeepCopyInto(out *NodeStorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStorageSpec.
func (in *NodeStorageSpec) DeepCopy() *NodeStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NodeStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgmiosSpec) DeepCopyInto(out *OgmiosSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgmiosSpec.
func (in *OgmiosSpec) DeepCopy() *OgmiosSpec {
	if in == nil {
		return nil
	}
	out := new(OgmiosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolVersionSpec) DeepCopyInto(out *ProtocolVersionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolVersionSpec.
func (in *ProtocolVersionSpec) DeepCopy() *ProtocolVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ProtocolVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicNetworkBootstrapSpec) DeepCopyInto(out *PublicNetworkBootstrapSpec) {
	*out = *in
	if in.Mithril != nil {
		in, out := &in.Mithril, &out.Mithril
		*out = new(MithrilBootstrapSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicNetworkBootstrapSpec.
func (in *PublicNetworkBootstrapSpec) DeepCopy() *PublicNetworkBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(PublicNetworkBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicNetworkSpec) DeepCopyInto(out *PublicNetworkSpec) {
	*out = *in
	if in.ConfigSource != nil {
		in, out := &in.ConfigSource, &out.ConfigSource
		*out = new(NetworkConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(PublicNetworkBootstrapSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicNetworkSpec.
func (in *PublicNetworkSpec) DeepCopy() *PublicNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(PublicNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointStatus) DeepCopyInto(out *ServiceEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointStatus.
func (in *ServiceEndpointStatus) DeepCopy() *ServiceEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointStatus)
	in.DeepCopyInto(out)
	return out
}
