//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetwork) DeepCopyInto(out *CardanoNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetwork.
func (in *CardanoNetwork) DeepCopy() *CardanoNetwork {
	if in == nil {
		return nil
	}
	out := new(CardanoNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CardanoNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkEndpointsStatus) DeepCopyInto(out *CardanoNetworkEndpointsStatus) {
	*out = *in
	if in.NodeToNode != nil {
		in, out := &in.NodeToNode, &out.NodeToNode
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
	if in.Ogmios != nil {
		in, out := &in.Ogmios, &out.Ogmios
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
	if in.Kupo != nil {
		in, out := &in.Kupo, &out.Kupo
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(ServiceEndpointStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkEndpointsStatus.
func (in *CardanoNetworkEndpointsStatus) DeepCopy() *CardanoNetworkEndpointsStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkEndpointsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkIdentityStatus) DeepCopyInto(out *CardanoNetworkIdentityStatus) {
	*out = *in
	if in.NetworkMagic != nil {
		in, out := &in.NetworkMagic, &out.NetworkMagic
		*out = new(int64)
		**out = **in
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(PublicNetworkProfile)
		**out = **in
	}
	if in.Era != nil {
		in, out := &in.Era, &out.Era
		*out = new(CardanoEra)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkIdentityStatus.
func (in *CardanoNetworkIdentityStatus) DeepCopy() *CardanoNetworkIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkList) DeepCopyInto(out *CardanoNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CardanoNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkList.
func (in *CardanoNetworkList) DeepCopy() *CardanoNetworkList {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CardanoNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkSpec) DeepCopyInto(out *CardanoNetworkSpec) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalNetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(PublicNetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ChainAPI != nil {
		in, out := &in.ChainAPI, &out.ChainAPI
		*out = new(ChainAPISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkSpec.
func (in *CardanoNetworkSpec) DeepCopy() *CardanoNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNetworkStatus) DeepCopyInto(out *CardanoNetworkStatus) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(CardanoNetworkIdentityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(CardanoNetworkEndpointsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(FaucetStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNetworkStatus.
func (in *CardanoNetworkStatus) DeepCopy() *CardanoNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(CardanoNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardanoNodeSpec) DeepCopyInto(out *CardanoNodeSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(NodeStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardanoNodeSpec.
func (in *CardanoNodeSpec) DeepCopy() *CardanoNodeSpec {
	if in == nil {
		return nil
	}
	out := new(CardanoNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainAPISpec) DeepCopyInto(out *ChainAPISpec) {
	*out = *in
	if in.Ogmios != nil {
		in, out := &in.Ogmios, &out.Ogmios
		*out = new(OgmiosSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kupo != nil {
		in, out := &in.Kupo, &out.Kupo
		*out = new(KupoSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(FaucetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainAPISpec.
func (in *ChainAPISpec) DeepCopy() *ChainAPISpec {
	if in == nil {
		return nil
	}
	out := new(ChainAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetSpec) DeepCopyInto(out *FaucetSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetSpec.
func (in *FaucetSpec) DeepCopy() *FaucetSpec {
	if in == nil {
		return nil
	}
	out := new(FaucetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetStatus) DeepCopyInto(out *FaucetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetStatus.
func (in *FaucetStatus) DeepCopy() *FaucetStatus {
	if in == nil {
		return nil
	}
	out := new(FaucetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KupoSpec) DeepCopyInto(out *KupoSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KupoSpec.
func (in *KupoSpec) DeepCopy() *KupoSpec {
	if in == nil {
		return nil
	}
	out := new(KupoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalGenesisSpec) DeepCopyInto(out *LocalGenesisSpec) {
	*out = *in
	if in.SecurityParameter != nil {
		in, out := &in.SecurityParameter, &out.SecurityParameter
		*out = new(int32)
		**out = **in
	}
	if in.MaxLovelaceSupply != nil {
		in, out := &in.MaxLovelaceSupply, &out.MaxLovelaceSupply
		*out = new(int64)
		**out = **in
	}
	if in.DelegatedSupply != nil {
		in, out := &in.DelegatedSupply, &out.DelegatedSupply
		*out = new(int64)
		**out = **in
	}
	if in.ProtocolVersion != nil {
		in, out := &in.ProtocolVersion, &out.ProtocolVersion
		*out = new(ProtocolVersionSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalGenesisSpec.
func (in *LocalGenesisSpec) DeepCopy() *LocalGenesisSpec {
	if in == nil {
		return nil
	}
	out := new(LocalGenesisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkSpec) DeepCopyInto(out *LocalNetworkSpec) {
	*out = *in
	out.Timing = in.Timing
	in.Topology.DeepCopyInto(&out.Topology)
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(LocalGenesisSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkSpec.
func (in *LocalNetworkSpec) DeepCopy() *LocalNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkTimingSpec) DeepCopyInto(out *LocalNetworkTimingSpec) {
	*out = *in
	out.SlotLength = in.SlotLength
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkTimingSpec.
func (in *LocalNetworkTimingSpec) DeepCopy() *LocalNetworkTimingSpec {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkTimingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkTopologySpec) DeepCopyInto(out *LocalNetworkTopologySpec) {
	*out = *in
	in.Pools.DeepCopyInto(&out.Pools)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkTopologySpec.
func (in *LocalNetworkTopologySpec) DeepCopy() *LocalNetworkTopologySpec {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPoolDefaultsSpec) DeepCopyInto(out *LocalPoolDefaultsSpec) {
	*out = *in
	if in.CostLovelace != nil {
		in, out := &in.CostLovelace, &out.CostLovelace
		*out = new(int64)
		**out = **in
	}
	if in.PledgeLovelace != nil {
		in, out := &in.PledgeLovelace, &out.PledgeLovelace
		*out = new(int64)
		**out = **in
	}
	if in.Margin != nil {
		in, out := &in.Margin, &out.Margin
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPoolDefaultsSpec.
func (in *LocalPoolDefaultsSpec) DeepCopy() *LocalPoolDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(LocalPoolDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPoolTopologySpec) DeepCopyInto(out *LocalPoolTopologySpec) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(LocalPoolDefaultsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPoolTopologySpec.
func (in *LocalPoolTopologySpec) DeepCopy() *LocalPoolTopologySpec {
	if in == nil {
		return nil
	}
	out := new(LocalPoolTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigSource) DeepCopyInto(out *NetworkConfigSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigSource.
func (in *NetworkConfigSource) DeepCopy() *NetworkConfigSource {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStorageSpec) DeepCopyInto(out *NodeStorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStorageSpec.
func (in *NodeStorageSpec) DeepCopy() *NodeStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NodeStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgmiosSpec) DeepCopyInto(out *OgmiosSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgmiosSpec.
func (in *OgmiosSpec) DeepCopy() *OgmiosSpec {
	if in == nil {
		return nil
	}
	out := new(OgmiosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolVersionSpec) DeepCopyInto(out *ProtocolVersionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolVersionSpec.
func (in *ProtocolVersionSpec) DeepCopy() *ProtocolVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ProtocolVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicNetworkSpec) DeepCopyInto(out *PublicNetworkSpec) {
	*out = *in
	if in.ConfigSource != nil {
		in, out := &in.ConfigSource, &out.ConfigSource
		*out = new(NetworkConfigSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicNetworkSpec.
func (in *PublicNetworkSpec) DeepCopy() *PublicNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(PublicNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointStatus) DeepCopyInto(out *ServiceEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointStatus.
func (in *ServiceEndpointStatus) DeepCopy() *ServiceEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointStatus)
	in.DeepCopyInto(out)
	return out
}
