// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/yacd/api/v1alpha1"
	"github.com/meigma/yacd/cli/internal/kube"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ApplyCardanoNetwork provides a mock function for the type Client
func (_mock *Client) ApplyCardanoNetwork(ctx context.Context, network *v1alpha1.CardanoNetwork) error {
	ret := _mock.Called(ctx, network)

	if len(ret) == 0 {
		panic("no return value specified for ApplyCardanoNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.CardanoNetwork) error); ok {
		r0 = returnFunc(ctx, network)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_ApplyCardanoNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyCardanoNetwork'
type Client_ApplyCardanoNetwork_Call struct {
	*mock.Call
}

// ApplyCardanoNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - network *v1alpha1.CardanoNetwork
func (_e *Client_Expecter) ApplyCardanoNetwork(ctx interface{}, network interface{}) *Client_ApplyCardanoNetwork_Call {
	return &Client_ApplyCardanoNetwork_Call{Call: _e.mock.On("ApplyCardanoNetwork", ctx, network)}
}

func (_c *Client_ApplyCardanoNetwork_Call) Run(run func(ctx context.Context, network *v1alpha1.CardanoNetwork)) *Client_ApplyCardanoNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.CardanoNetwork
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.CardanoNetwork)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_ApplyCardanoNetwork_Call) Return(err error) *Client_ApplyCardanoNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_ApplyCardanoNetwork_Call) RunAndReturn(run func(ctx context.Context, network *v1alpha1.CardanoNetwork) error) *Client_ApplyCardanoNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultNamespace provides a mock function for the type Client
func (_mock *Client) DefaultNamespace() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultNamespace")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Client_DefaultNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultNamespace'
type Client_DefaultNamespace_Call struct {
	*mock.Call
}

// DefaultNamespace is a helper method to define mock.On call
func (_e *Client_Expecter) DefaultNamespace() *Client_DefaultNamespace_Call {
	return &Client_DefaultNamespace_Call{Call: _e.mock.On("DefaultNamespace")}
}

func (_c *Client_DefaultNamespace_Call) Run(run func()) *Client_DefaultNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_DefaultNamespace_Call) Return(s string) *Client_DefaultNamespace_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Client_DefaultNamespace_Call) RunAndReturn(run func() string) *Client_DefaultNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCardanoNetwork provides a mock function for the type Client
func (_mock *Client) DeleteCardanoNetwork(ctx context.Context, namespace string, name string) error {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCardanoNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteCardanoNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCardanoNetwork'
type Client_DeleteCardanoNetwork_Call struct {
	*mock.Call
}

// DeleteCardanoNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *Client_Expecter) DeleteCardanoNetwork(ctx interface{}, namespace interface{}, name interface{}) *Client_DeleteCardanoNetwork_Call {
	return &Client_DeleteCardanoNetwork_Call{Call: _e.mock.On("DeleteCardanoNetwork", ctx, namespace, name)}
}

func (_c *Client_DeleteCardanoNetwork_Call) Run(run func(ctx context.Context, namespace string, name string)) *Client_DeleteCardanoNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_DeleteCardanoNetwork_Call) Return(err error) *Client_DeleteCardanoNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteCardanoNetwork_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) error) *Client_DeleteCardanoNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureNamespace provides a mock function for the type Client
func (_mock *Client) EnsureNamespace(ctx context.Context, namespace string) error {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for EnsureNamespace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_EnsureNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureNamespace'
type Client_EnsureNamespace_Call struct {
	*mock.Call
}

// EnsureNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *Client_Expecter) EnsureNamespace(ctx interface{}, namespace interface{}) *Client_EnsureNamespace_Call {
	return &Client_EnsureNamespace_Call{Call: _e.mock.On("EnsureNamespace", ctx, namespace)}
}

func (_c *Client_EnsureNamespace_Call) Run(run func(ctx context.Context, namespace string)) *Client_EnsureNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_EnsureNamespace_Call) Return(err error) *Client_EnsureNamespace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_EnsureNamespace_Call) RunAndReturn(run func(ctx context.Context, namespace string) error) *Client_EnsureNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type Client
func (_mock *Client) Exec(ctx context.Context, req kube.ExecRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kube.ExecRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type Client_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - req kube.ExecRequest
func (_e *Client_Expecter) Exec(ctx interface{}, req interface{}) *Client_Exec_Call {
	return &Client_Exec_Call{Call: _e.mock.On("Exec", ctx, req)}
}

func (_c *Client_Exec_Call) Run(run func(ctx context.Context, req kube.ExecRequest)) *Client_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kube.ExecRequest
		if args[1] != nil {
			arg1 = args[1].(kube.ExecRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_Exec_Call) Return(err error) *Client_Exec_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Exec_Call) RunAndReturn(run func(ctx context.Context, req kube.ExecRequest) error) *Client_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Forward provides a mock function for the type Client
func (_mock *Client) Forward(ctx context.Context, namespace string, podName string, specs []kube.PortForwardSpec) (kube.ForwardSession, error) {
	ret := _mock.Called(ctx, namespace, podName, specs)

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 kube.ForwardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []kube.PortForwardSpec) (kube.ForwardSession, error)); ok {
		return returnFunc(ctx, namespace, podName, specs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []kube.PortForwardSpec) kube.ForwardSession); ok {
		r0 = returnFunc(ctx, namespace, podName, specs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kube.ForwardSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []kube.PortForwardSpec) error); ok {
		r1 = returnFunc(ctx, namespace, podName, specs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type Client_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - specs []kube.PortForwardSpec
func (_e *Client_Expecter) Forward(ctx interface{}, namespace interface{}, podName interface{}, specs interface{}) *Client_Forward_Call {
	return &Client_Forward_Call{Call: _e.mock.On("Forward", ctx, namespace, podName, specs)}
}

func (_c *Client_Forward_Call) Run(run func(ctx context.Context, namespace string, podName string, specs []kube.PortForwardSpec)) *Client_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []kube.PortForwardSpec
		if args[3] != nil {
			arg3 = args[3].([]kube.PortForwardSpec)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_Forward_Call) Return(forwardSession kube.ForwardSession, err error) *Client_Forward_Call {
	_c.Call.Return(forwardSession, err)
	return _c
}

func (_c *Client_Forward_Call) RunAndReturn(run func(ctx context.Context, namespace string, podName string, specs []kube.PortForwardSpec) (kube.ForwardSession, error)) *Client_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// GetCardanoNetwork provides a mock function for the type Client
func (_mock *Client) GetCardanoNetwork(ctx context.Context, namespace string, name string) (*v1alpha1.CardanoNetwork, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCardanoNetwork")
	}

	var r0 *v1alpha1.CardanoNetwork
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.CardanoNetwork, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.CardanoNetwork); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CardanoNetwork)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetCardanoNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardanoNetwork'
type Client_GetCardanoNetwork_Call struct {
	*mock.Call
}

// GetCardanoNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *Client_Expecter) GetCardanoNetwork(ctx interface{}, namespace interface{}, name interface{}) *Client_GetCardanoNetwork_Call {
	return &Client_GetCardanoNetwork_Call{Call: _e.mock.On("GetCardanoNetwork", ctx, namespace, name)}
}

func (_c *Client_GetCardanoNetwork_Call) Run(run func(ctx context.Context, namespace string, name string)) *Client_GetCardanoNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetCardanoNetwork_Call) Return(cardanoNetwork *v1alpha1.CardanoNetwork, err error) *Client_GetCardanoNetwork_Call {
	_c.Call.Return(cardanoNetwork, err)
	return _c
}

func (_c *Client_GetCardanoNetwork_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*v1alpha1.CardanoNetwork, error)) *Client_GetCardanoNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretValue provides a mock function for the type Client
func (_mock *Client) GetSecretValue(ctx context.Context, namespace string, name string, key string) (string, error) {
	ret := _mock.Called(ctx, namespace, name, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, namespace, name, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, namespace, name, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretValue'
type Client_GetSecretValue_Call struct {
	*mock.Call
}

// GetSecretValue is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - key string
func (_e *Client_Expecter) GetSecretValue(ctx interface{}, namespace interface{}, name interface{}, key interface{}) *Client_GetSecretValue_Call {
	return &Client_GetSecretValue_Call{Call: _e.mock.On("GetSecretValue", ctx, namespace, name, key)}
}

func (_c *Client_GetSecretValue_Call) Run(run func(ctx context.Context, namespace string, name string, key string)) *Client_GetSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_GetSecretValue_Call) Return(s string, err error) *Client_GetSecretValue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_GetSecretValue_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string, key string) (string, error)) *Client_GetSecretValue_Call {
	_c.Call.Return(run)
	return _c
}

// ListCardanoNetworks provides a mock function for the type Client
func (_mock *Client) ListCardanoNetworks(ctx context.Context, namespace string) ([]v1alpha1.CardanoNetwork, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListCardanoNetworks")
	}

	var r0 []v1alpha1.CardanoNetwork
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]v1alpha1.CardanoNetwork, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []v1alpha1.CardanoNetwork); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha1.CardanoNetwork)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_ListCardanoNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCardanoNetworks'
type Client_ListCardanoNetworks_Call struct {
	*mock.Call
}

// ListCardanoNetworks is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *Client_Expecter) ListCardanoNetworks(ctx interface{}, namespace interface{}) *Client_ListCardanoNetworks_Call {
	return &Client_ListCardanoNetworks_Call{Call: _e.mock.On("ListCardanoNetworks", ctx, namespace)}
}

func (_c *Client_ListCardanoNetworks_Call) Run(run func(ctx context.Context, namespace string)) *Client_ListCardanoNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_ListCardanoNetworks_Call) Return(cardanoNetworks []v1alpha1.CardanoNetwork, err error) *Client_ListCardanoNetworks_Call {
	_c.Call.Return(cardanoNetworks, err)
	return _c
}

func (_c *Client_ListCardanoNetworks_Call) RunAndReturn(run func(ctx context.Context, namespace string) ([]v1alpha1.CardanoNetwork, error)) *Client_ListCardanoNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// PrimaryPodName provides a mock function for the type Client
func (_mock *Client) PrimaryPodName(ctx context.Context, namespace string, networkName string) (string, error) {
	ret := _mock.Called(ctx, namespace, networkName)

	if len(ret) == 0 {
		panic("no return value specified for PrimaryPodName")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, namespace, networkName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, namespace, networkName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, networkName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_PrimaryPodName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrimaryPodName'
type Client_PrimaryPodName_Call struct {
	*mock.Call
}

// PrimaryPodName is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - networkName string
func (_e *Client_Expecter) PrimaryPodName(ctx interface{}, namespace interface{}, networkName interface{}) *Client_PrimaryPodName_Call {
	return &Client_PrimaryPodName_Call{Call: _e.mock.On("PrimaryPodName", ctx, namespace, networkName)}
}

func (_c *Client_PrimaryPodName_Call) Run(run func(ctx context.Context, namespace string, networkName string)) *Client_PrimaryPodName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_PrimaryPodName_Call) Return(s string, err error) *Client_PrimaryPodName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_PrimaryPodName_Call) RunAndReturn(run func(ctx context.Context, namespace string, networkName string) (string, error)) *Client_PrimaryPodName_Call {
	_c.Call.Return(run)
	return _c
}
