// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewForwardSession creates a new instance of ForwardSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForwardSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForwardSession {
	mock := &ForwardSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ForwardSession is an autogenerated mock type for the ForwardSession type
type ForwardSession struct {
	mock.Mock
}

type ForwardSession_Expecter struct {
	mock *mock.Mock
}

func (_m *ForwardSession) EXPECT() *ForwardSession_Expecter {
	return &ForwardSession_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ForwardSession
func (_mock *ForwardSession) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ForwardSession_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ForwardSession_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ForwardSession_Expecter) Close() *ForwardSession_Close_Call {
	return &ForwardSession_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ForwardSession_Close_Call) Run(run func()) *ForwardSession_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ForwardSession_Close_Call) Return(err error) *ForwardSession_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ForwardSession_Close_Call) RunAndReturn(run func() error) *ForwardSession_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type ForwardSession
func (_mock *ForwardSession) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// ForwardSession_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type ForwardSession_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *ForwardSession_Expecter) Done() *ForwardSession_Done_Call {
	return &ForwardSession_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *ForwardSession_Done_Call) Run(run func()) *ForwardSession_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ForwardSession_Done_Call) Return(valCh <-chan struct{}) *ForwardSession_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *ForwardSession_Done_Call) RunAndReturn(run func() <-chan struct{}) *ForwardSession_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type ForwardSession
func (_mock *ForwardSession) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ForwardSession_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type ForwardSession_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *ForwardSession_Expecter) Err() *ForwardSession_Err_Call {
	return &ForwardSession_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *ForwardSession_Err_Call) Run(run func()) *ForwardSession_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ForwardSession_Err_Call) Return(err error) *ForwardSession_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ForwardSession_Err_Call) RunAndReturn(run func() error) *ForwardSession_Err_Call {
	_c.Call.Return(run)
	return _c
}

// LocalPort provides a mock function for the type ForwardSession
func (_mock *ForwardSession) LocalPort(remote int32) (int, bool) {
	ret := _mock.Called(remote)

	if len(ret) == 0 {
		panic("no return value specified for LocalPort")
	}

	var r0 int
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(int32) (int, bool)); ok {
		return returnFunc(remote)
	}
	if returnFunc, ok := ret.Get(0).(func(int32) int); ok {
		r0 = returnFunc(remote)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(int32) bool); ok {
		r1 = returnFunc(remote)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ForwardSession_LocalPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalPort'
type ForwardSession_LocalPort_Call struct {
	*mock.Call
}

// LocalPort is a helper method to define mock.On call
//   - remote int32
func (_e *ForwardSession_Expecter) LocalPort(remote interface{}) *ForwardSession_LocalPort_Call {
	return &ForwardSession_LocalPort_Call{Call: _e.mock.On("LocalPort", remote)}
}

func (_c *ForwardSession_LocalPort_Call) Run(run func(remote int32)) *ForwardSession_LocalPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ForwardSession_LocalPort_Call) Return(n int, b bool) *ForwardSession_LocalPort_Call {
	_c.Call.Return(n, b)
	return _c
}

func (_c *ForwardSession_LocalPort_Call) RunAndReturn(run func(remote int32) (int, bool)) *ForwardSession_LocalPort_Call {
	_c.Call.Return(run)
	return _c
}
