// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/yacd/cli/internal/operator"
	mock "github.com/stretchr/testify/mock"
)

// NewInstaller creates a new instance of Installer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *Installer {
	mock := &Installer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Installer is an autogenerated mock type for the Installer type
type Installer struct {
	mock.Mock
}

type Installer_Expecter struct {
	mock *mock.Mock
}

func (_m *Installer) EXPECT() *Installer_Expecter {
	return &Installer_Expecter{mock: &_m.Mock}
}

// EnsureOperator provides a mock function for the type Installer
func (_mock *Installer) EnsureOperator(ctx context.Context, spec operator.InstallSpec) (operator.State, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for EnsureOperator")
	}

	var r0 operator.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operator.InstallSpec) (operator.State, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operator.InstallSpec) operator.State); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(operator.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operator.InstallSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Installer_EnsureOperator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureOperator'
type Installer_EnsureOperator_Call struct {
	*mock.Call
}

// EnsureOperator is a helper method to define mock.On call
//   - ctx context.Context
//   - spec operator.InstallSpec
func (_e *Installer_Expecter) EnsureOperator(ctx interface{}, spec interface{}) *Installer_EnsureOperator_Call {
	return &Installer_EnsureOperator_Call{Call: _e.mock.On("EnsureOperator", ctx, spec)}
}

func (_c *Installer_EnsureOperator_Call) Run(run func(ctx context.Context, spec operator.InstallSpec)) *Installer_EnsureOperator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operator.InstallSpec
		if args[1] != nil {
			arg1 = args[1].(operator.InstallSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Installer_EnsureOperator_Call) Return(state operator.State, err error) *Installer_EnsureOperator_Call {
	_c.Call.Return(state, err)
	return _c
}

func (_c *Installer_EnsureOperator_Call) RunAndReturn(run func(ctx context.Context, spec operator.InstallSpec) (operator.State, error)) *Installer_EnsureOperator_Call {
	_c.Call.Return(run)
	return _c
}

// OperatorState provides a mock function for the type Installer
func (_mock *Installer) OperatorState(ctx context.Context) (operator.State, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OperatorState")
	}

	var r0 operator.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (operator.State, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) operator.State); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(operator.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Installer_OperatorState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OperatorState'
type Installer_OperatorState_Call struct {
	*mock.Call
}

// OperatorState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Installer_Expecter) OperatorState(ctx interface{}) *Installer_OperatorState_Call {
	return &Installer_OperatorState_Call{Call: _e.mock.On("OperatorState", ctx)}
}

func (_c *Installer_OperatorState_Call) Run(run func(ctx context.Context)) *Installer_OperatorState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Installer_OperatorState_Call) Return(state operator.State, err error) *Installer_OperatorState_Call {
	_c.Call.Return(state, err)
	return _c
}

func (_c *Installer_OperatorState_Call) RunAndReturn(run func(ctx context.Context) (operator.State, error)) *Installer_OperatorState_Call {
	_c.Call.Return(run)
	return _c
}
