// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/yacd/cli/internal/cluster"
	mock "github.com/stretchr/testify/mock"
)

// NewProvisioner creates a new instance of Provisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provisioner {
	mock := &Provisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Provisioner is an autogenerated mock type for the Provisioner type
type Provisioner struct {
	mock.Mock
}

type Provisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *Provisioner) EXPECT() *Provisioner_Expecter {
	return &Provisioner_Expecter{mock: &_m.Mock}
}

// DeleteCluster provides a mock function for the type Provisioner
func (_mock *Provisioner) DeleteCluster(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Provisioner_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type Provisioner_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Provisioner_Expecter) DeleteCluster(ctx interface{}, name interface{}) *Provisioner_DeleteCluster_Call {
	return &Provisioner_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", ctx, name)}
}

func (_c *Provisioner_DeleteCluster_Call) Run(run func(ctx context.Context, name string)) *Provisioner_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Provisioner_DeleteCluster_Call) Return(err error) *Provisioner_DeleteCluster_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Provisioner_DeleteCluster_Call) RunAndReturn(run func(ctx context.Context, name string) error) *Provisioner_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureCluster provides a mock function for the type Provisioner
func (_mock *Provisioner) EnsureCluster(ctx context.Context, spec cluster.Spec) (cluster.Info, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for EnsureCluster")
	}

	var r0 cluster.Info
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cluster.Spec) (cluster.Info, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cluster.Spec) cluster.Info); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(cluster.Info)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cluster.Spec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Provisioner_EnsureCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureCluster'
type Provisioner_EnsureCluster_Call struct {
	*mock.Call
}

// EnsureCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - spec cluster.Spec
func (_e *Provisioner_Expecter) EnsureCluster(ctx interface{}, spec interface{}) *Provisioner_EnsureCluster_Call {
	return &Provisioner_EnsureCluster_Call{Call: _e.mock.On("EnsureCluster", ctx, spec)}
}

func (_c *Provisioner_EnsureCluster_Call) Run(run func(ctx context.Context, spec cluster.Spec)) *Provisioner_EnsureCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cluster.Spec
		if args[1] != nil {
			arg1 = args[1].(cluster.Spec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Provisioner_EnsureCluster_Call) Return(info cluster.Info, err error) *Provisioner_EnsureCluster_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *Provisioner_EnsureCluster_Call) RunAndReturn(run func(ctx context.Context, spec cluster.Spec) (cluster.Info, error)) *Provisioner_EnsureCluster_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type Provisioner
func (_mock *Provisioner) Status(ctx context.Context, name string, kubeconfigPath string) (cluster.Status, error) {
	ret := _mock.Called(ctx, name, kubeconfigPath)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 cluster.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (cluster.Status, error)); ok {
		return returnFunc(ctx, name, kubeconfigPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) cluster.Status); ok {
		r0 = returnFunc(ctx, name, kubeconfigPath)
	} else {
		r0 = ret.Get(0).(cluster.Status)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, kubeconfigPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Provisioner_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type Provisioner_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - kubeconfigPath string
func (_e *Provisioner_Expecter) Status(ctx interface{}, name interface{}, kubeconfigPath interface{}) *Provisioner_Status_Call {
	return &Provisioner_Status_Call{Call: _e.mock.On("Status", ctx, name, kubeconfigPath)}
}

func (_c *Provisioner_Status_Call) Run(run func(ctx context.Context, name string, kubeconfigPath string)) *Provisioner_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Provisioner_Status_Call) Return(status cluster.Status, err error) *Provisioner_Status_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *Provisioner_Status_Call) RunAndReturn(run func(ctx context.Context, name string, kubeconfigPath string) (cluster.Status, error)) *Provisioner_Status_Call {
	_c.Call.Return(run)
	return _c
}
