// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/yacd/cli/internal/clusterstate"
	mock "github.com/stretchr/testify/mock"
)

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type Store
func (_mock *Store) Clear() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type Store_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *Store_Expecter) Clear() *Store_Clear_Call {
	return &Store_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *Store_Clear_Call) Run(run func()) *Store_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_Clear_Call) Return(err error) *Store_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_Clear_Call) RunAndReturn(run func() error) *Store_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type Store
func (_mock *Store) Load() (clusterstate.Record, bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 clusterstate.Record
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (clusterstate.Record, bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() clusterstate.Record); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(clusterstate.Record)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Store_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Store_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *Store_Expecter) Load() *Store_Load_Call {
	return &Store_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *Store_Load_Call) Run(run func()) *Store_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_Load_Call) Return(record clusterstate.Record, b bool, err error) *Store_Load_Call {
	_c.Call.Return(record, b, err)
	return _c
}

func (_c *Store_Load_Call) RunAndReturn(run func() (clusterstate.Record, bool, error)) *Store_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type Store
func (_mock *Store) Lock(ctx context.Context) (func() error, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 func() error
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (func() error, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) func() error); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type Store_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) Lock(ctx interface{}) *Store_Lock_Call {
	return &Store_Lock_Call{Call: _e.mock.On("Lock", ctx)}
}

func (_c *Store_Lock_Call) Run(run func(ctx context.Context)) *Store_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_Lock_Call) Return(release func() error, err error) *Store_Lock_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *Store_Lock_Call) RunAndReturn(run func(ctx context.Context) (func() error, error)) *Store_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type Store
func (_mock *Store) Save(record clusterstate.Record) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(clusterstate.Record) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Store_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - record clusterstate.Record
func (_e *Store_Expecter) Save(record interface{}) *Store_Save_Call {
	return &Store_Save_Call{Call: _e.mock.On("Save", record)}
}

func (_c *Store_Save_Call) Run(run func(record clusterstate.Record)) *Store_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 clusterstate.Record
		if args[0] != nil {
			arg0 = args[0].(clusterstate.Record)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_Save_Call) Return(err error) *Store_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_Save_Call) RunAndReturn(run func(record clusterstate.Record) error) *Store_Save_Call {
	_c.Call.Return(run)
	return _c
}
