// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/yacd/internal/cardano/tx"
	mock "github.com/stretchr/testify/mock"
)

// NewSubmitter creates a new instance of Submitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Submitter {
	mock := &Submitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Submitter is an autogenerated mock type for the Submitter type
type Submitter struct {
	mock.Mock
}

type Submitter_Expecter struct {
	mock *mock.Mock
}

func (_m *Submitter) EXPECT() *Submitter_Expecter {
	return &Submitter_Expecter{mock: &_m.Mock}
}

// Submit provides a mock function for the type Submitter
func (_mock *Submitter) Submit(ctx context.Context, request tx.Request) (tx.Result, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 tx.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tx.Request) (tx.Result, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tx.Request) tx.Result); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(tx.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tx.Request) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Submitter_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type Submitter_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - request tx.Request
func (_e *Submitter_Expecter) Submit(ctx interface{}, request interface{}) *Submitter_Submit_Call {
	return &Submitter_Submit_Call{Call: _e.mock.On("Submit", ctx, request)}
}

func (_c *Submitter_Submit_Call) Run(run func(ctx context.Context, request tx.Request)) *Submitter_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tx.Request
		if args[1] != nil {
			arg1 = args[1].(tx.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Submitter_Submit_Call) Return(result tx.Result, err error) *Submitter_Submit_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *Submitter_Submit_Call) RunAndReturn(run func(ctx context.Context, request tx.Request) (tx.Result, error)) *Submitter_Submit_Call {
	_c.Call.Return(run)
	return _c
}
