apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: yacd-registry
port: 5005
listenAddress: 127.0.0.1
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-yacd-dev
product: kind
registry: yacd-registry
kindV1Alpha4Cluster:
  nodes:
    - role: control-plane
